export const KPI_PENDIENTES_REQUEST = 'KPI_PENDIENTES_REQUEST';
export const KPI_PENDIENTES_SUCCESS = 'KPI_PENDIENTES_SUCCESS';
export const KPI_PENDIENTES_FAIL = 'KPI_PENDIENTES_FAIL';

export const KPI_CREAR_PENDIENTES_REQUEST = 'KPI_CREAR_PENDIENTES_REQUEST';
export const KPI_CREAR_PENDIENTES_SUCCESS = 'KPI_CREAR_PENDIENTES_SUCCESS';
export const KPI_CREAR_PENDIENTES_FAIL = 'KPI_CREAR_PENDIENTES_FAIL';

export const KPI_ACTUALIZAR_PENDIENTES_REQUEST = 'KPI_ACTUALIZAR_PENDIENTES_REQUEST';
export const KPI_ACTUALIZAR_PENDIENTES_SUCCESS = 'KPI_ACTUALIZAR_PENDIENTES_SUCCESS';
export const KPI_ACTUALIZAR_PENDIENTES_FAIL = 'KPI_ACTUALIZAR_PENDIENTES_FAIL';

export const KPI_MODIFICAR_PENDIENTES_REQUEST = 'KPI_MODIFICAR_PENDIENTES_REQUEST';
export const KPI_MODIFICAR_PENDIENTES_SUCCESS = 'KPI_MODIFICAR_PENDIENTES_SUCCESS';
export const KPI_MODIFICAR_PENDIENTES_FAIL = 'KPI_MODIFICAR_PENDIENTES_FAIL';

export const KPI_DELETE_PENDIENTES_REQUEST = 'KPI_DELETE_PENDIENTES_REQUEST';
export const KPI_DELETE_PENDIENTES_SUCCESS = 'KPI_DELETE_PENDIENTES_SUCCESS';
export const KPI_DELETE_PENDIENTES_FAIL = 'KPI_DELETE_PENDIENTES_FAIL';

export const KPI_GRUPO_LISTA_REQUEST = 'KPI_GRUPO_LISTA_REQUEST';
export const KPI_GRUPO_LISTA_SUCCESS = 'KPI_GRUPO_LISTA_SUCCESS';
export const KPI_GRUPO_LISTA_FAIL = 'KPI_GRUPO_LISTA_FAIL';

export const KPI_LIST_REQUEST = 'KPI_LIST_REQUEST';
export const KPI_LIST_SUCCESS = 'KPI_LIST_SUCCESS';
export const KPI_LIST_FAIL = 'KPI_LIST_FAIL';

export const KPI_USER_DETALLE_REQUEST = 'KPI_USER_DETALLE_REQUEST';
export const KPI_USER_DETALLE_SUCCESS = 'KPI_USER_DETALLE_SUCCESS';
export const KPI_USER_DETALLE_FAIL = 'KPI_USER_DETALLE_FAIL';

export const KPI_USER_CAMBIO_JORNADA_HORA_REQUEST = 'KPI_USER_CAMBIO_JORNADA_HORA_REQUEST';
export const KPI_USER_CAMBIO_JORNADA_HORA_SUCCESS = 'KPI_USER_CAMBIO_JORNADA_HORA_SUCCESS';
export const KPI_USER_CAMBIO_JORNADA_HORA_FAIL = 'KPI_USER_CAMBIO_JORNADA_HORA_FAIL';

export const KPI_USER_CAMBIO_JORNADA_MIN_REQUEST = 'KPI_USER_CAMBIO_JORNADA_MIN_REQUEST';
export const KPI_USER_CAMBIO_JORNADA_MIN_SUCCESS = 'KPI_USER_CAMBIO_JORNADA_MIN_SUCCESS';
export const KPI_USER_CAMBIO_JORNADA_MIN_FAIL = 'KPI_USER_CAMBIO_JORNADA_MIN_FAIL';

export const KPI_HORA_VISTA_REQUEST = 'KPI_HORA_VISTA_REQUEST';
export const KPI_HORA_VISTA_SUCCESS = 'KPI_HORA_VISTA_SUCCESS';
export const KPI_HORA_VISTA_FAIL = 'KPI_HORA_VISTA_FAIL';


