  
export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_PROYECTO_REQUEST = 'USER_PROYECTO_REQUEST';
export const USER_PROYECTO_SUCCESS = 'USER_PROYECTO_SUCCESS';
export const USER_PROYECTO_FAIL = 'USER_PROYECTO_FAIL';

export const USER_PROYECTO_DETALLES_REQUEST = 'USER_PROYECTO_DETALLES_REQUEST';
export const USER_PROYECTO_DETALLES_SUCCESS = 'USER_PROYECTO_DETALLES_SUCCESS';
export const USER_PROYECTO_DETALLES_FAIL = 'USER_PROYECTO_DETALLES_FAIL';

export const USER_ENTRADA_REQUEST = 'USER_ENTRADA_REQUEST';
export const USER_ENTRADA_SUCCESS = 'USER_ENTRADA_SUCCESS';
export const USER_ENTRADA_FAIL = 'USER_ENTRADA_FAIL';

export const USER_SALIDA_REQUEST = 'USER_SALIDA_REQUEST';
export const USER_SALIDA_SUCCESS = 'USER_SALIDA_SUCCESS';
export const USER_SALIDA_FAIL = 'USER_SALIDA_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_INFO_REGISTER_REQUEST = 'USER_INFO_REGISTER_REQUEST';
export const USER_INFO_REGISTER_SUCCESS = 'USER_INFO_REGISTER_SUCCESS';
export const USER_INFO_REGISTER_FAIL = 'USER_INFO_REGISTER_FAIL';

export const USER_INFO_ACTUALIZAR_REQUEST = 'USER_INFO_ACTUALIZAR_REQUEST';
export const USER_INFO_ACTUALIZAR_SUCCESS = 'USER_INFO_ACTUALIZAR_SUCCESS';
export const USER_INFO_ACTUALIZAR_FAIL = 'USER_INFO_ACTUALIZAR_FAIL';

export const USER_INFO_ACTUALIZAR_NOMBRE_REQUEST = 'USER_INFO_ACTUALIZAR_NOMBRE_REQUEST';
export const USER_INFO_ACTUALIZAR_NOMBRE_SUCCESS = 'USER_INFO_ACTUALIZAR_NOMBRE_SUCCESS';
export const USER_INFO_ACTUALIZAR_NOMBRE_FAIL = 'USER_INFO_ACTUALIZAR_NOMBRE_FAIL';

export const USER_ALMUERZO_REQUEST = 'USER_ALMUERZO_REQUEST';
export const USER_ALMUERZO_SUCCESS = 'USER_ALMUERZO_SUCCESS';
export const USER_ALMUERZO_FAIL = 'USER_ALMUERZO_FAIL';

export const USER_PERMISO_REQUEST = 'USER_PERMISO_REQUEST';
export const USER_PERMISO_SUCCESS = 'USER_PERMISO_SUCCESS';
export const USER_PERMISO_FAIL = 'USER_PERMISO_FAIL';

export const USER_STATUS_REQUEST = 'USER_STATUS_REQUEST';
export const USER_STATUS_SUCCESS = 'USER_STATUS_SUCCESS';
export const USER_STATUS_FAIL = 'USER_STATUS_FAIL';
  
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_CREATE_FAIL = 'USER_CREATE_FAIL';

export const USER_CHGPASS_REQUEST = 'USER_CHGPASS_REQUEST';
export const USER_CHGPASS_SUCCESS = 'USER_CHGPASS_SUCCESS';
export const USER_CHGPASS_FAIL = 'USER_CHGPASS_FAIL';

export const USER_RECOVERY_REQUEST = 'USER_RECOVERY_REQUEST';
export const USER_RECOVERY_SUCCESS = 'USER_RECOVERY_SUCCESS';
export const USER_RECOVERY_FAIL = 'USER_RECOVERY_FAIL';

export const USER_MARCARLEIDO_REQUEST = 'USER_MARCARLEIDO_REQUEST';
export const USER_MARCARLEIDO_SUCCESS = 'USER_MARCARLEIDO_SUCCESS';
export const USER_MARCARLEIDO_FAIL = 'USER_MARCARLEIDO_FAIL';

export const USER_SAVE_ACTUALIZAR_REQUEST = 'USER_SAVE_ACTUALIZAR_REQUEST';
export const USER_SAVE_ACTUALIZAR_SUCCESS = 'USER_SAVE_ACTUALIZAR_SUCCESS';
export const USER_SAVE_ACTUALIZAR_FAIL = 'USER_SAVE_ACTUALIZAR_FAIL';

export const USER_INFO_ACTUALIZAR_KPI_REQUEST = 'USER_INFO_ACTUALIZAR_KPI_REQUEST';
export const USER_INFO_ACTUALIZAR_KPI_SUCCESS = 'USER_INFO_ACTUALIZAR_KPI_SUCCESS';
export const USER_INFO_ACTUALIZAR_KPI_FAIL = 'USER_INFO_ACTUALIZAR_KPI_FAIL';

export const USER_INFO_KPI_GET_REQUEST = 'USER_INFO_KPI_GET_REQUEST';
export const USER_INFO_KPI_GET_SUCCESS = 'USER_INFO_KPI_GET_SUCCESS';
export const USER_INFO_KPI_GET_FAIL = 'USER_INFO_KPI_GET_FAIL';

export const USER_OTS_REQUEST = 'USER_OTS_REQUEST';
export const USER_OTS_SUCCESS = 'USER_OTS_SUCCESS';
export const USER_OTS_FAIL = 'USER_OTS_FAIL';